---
- name: Update main MySQL configuration
  ansible.builtin.template:
    src: my.cnf
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: '0644'
  notify: Restart service mysqld

- name: Update MySQL configuration
  ansible.builtin.template:
    src: my.cnf.d/{{ item }}
    dest: /etc/my.cnf.d/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop: '{{ query("ansible.builtin.fileglob", role_path +
    "/templates/my.cnf.d/*") | map("ansible.builtin.basename") }}'
  notify: Restart service mysqld
...
