---
mysql_export_socket: /var/lib/mysql/mysql.sock
mysql_export_user: root
mysql_export_password: '{{ lookup("ansible.builtin.password",
  "passwords/mysql_root_password.txt", length=26) }}'

mysql_export_databases: {}
...
